greeting:
  message: "Hello from Config Server"
database:
  password: "{cipher}AQBEPUnBLEiB6FfcsMW84DOla0mJAATlvWm7KUmEGTT/u4hoV54bfNTemGwhzYdVUycHrBCrOr6h+D5qC08KQRDEwXt251/V7vLrg0+uCCI+b2eAdSTwfuL6xe5wyjNqOHChl9ISsLzG7shpsbYUZLTAgm2hHYph4HSxhXkKxOjYGIqjlZ2+7G8qBuVQpvcB9x8+7/g7WbSOc7S4/tFLloPj0wRjbnGoJAXsPZD6/91r/3N4SyPnU+NBGFdJjtJxRNS8gSC/iTWZhYfE7G5blXlWfkg99EZhxMimkgQU1gFNuNdNogjbvBcw/8U8xdDpaMxFlF1BChyp+HjNadWWXNiaIdJHHqmG7iShgxkXg+J/CBsiR6ICFWa9OeetccXk4slKQZaTLpLWU73DcGeP42Gk%" 
